# Generated by Django 5.2.7 on 2025-10-31 21:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name_unique_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('stock_count__gt', 0)), name='stock_count_must_be_gt0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_must_be_gt0'),
        ),
    ]
